{% set name = "flake8-import-order" %}
{% set version = "0.15" %}
{% set sha256 = "fd8608a29df93589ecbe5281981222929261c915068f2aedfb51f243f05f5466" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - asttokens
    - pycodestyle
    - flake8

test:
  commands:
    - "flake8 --version | grep import-order:"

about:
  home: https://github.com/PyCQA/flake8-import-order
  license: LGPL-3.0
  license_family: LGPL
  license_file: COPYING
  summary: 'A flake8 and Pylama plugin that checks the ordering of your imports.'

  description: |
          A flake8 and Pylama plugin that checks the ordering of your imports.
          In general stdlib comes first, then 3rd party, then local packages,
          and that each group is individually alphabetized, see Configuration
          section for details. It will not check anything else about the
          imports. Merely that they are grouped and ordered correctly. This
          plugin is under somewhat active development and is heavily influenced
          by the personal preferences of the developers of cryptography. Expect
          seemingly random changes and configuration changes as we figure out
          how it should work.
  dev_url: https://github.com/PyCQA/flake8-import-order

extra:
  recipe-maintainers:
    - dopplershift
