travis:
  secure:
    BINSTAR_TOKEN: mVVRJp8aHQj8QcJDqn1GQ712yh/AweDsEYTHR7px3X5RgPC1vccVzOrSLfIJ/vDJ8wCmCY8S8ZmFlg8TWYTbAaPReU3mjQww0eCJosRjaxDvwChpDe+68DuQmyYDET3SsE64FqCRQsB0b8s7DThSOBlqAa9sVNMB048C+CvYT+N+GaThUr9L956mxiskrvTyS/c+kwGJYip394Og3GCCqdnU8gwWVu9p5FICJzBTfNV8IrkLtIKOlqR6nKul24HxwY3l2T7pQuUWioXA4YIEU3HZK9lQ8iVmbXFIKTTu+MPwrBRFodDHMP69xx8ftZZ5H2dNlpyhjirYzFJMPT9bCHS3oQgOW9orWT+tMEN9bA15I7cRHjRDTAaC8jjlMeoXN5ZBkNDf9cX1H7E1KR365dzzuv6zWW/9upic3wAqMwGAXICH2SVGPhmrYW0H855pNuWV2gWZlHWZdo3MdWqwMvICW+uIs1swriaDkYIpFsxEHH79KgdP1S3PCV9EHFatAZAg4+Z2dN7ZWMCM0RtD/WyiJnJC3hxPVyu/QYvzZeQ4Me9Pe1GZDUweTg7Z/I9ft7XCZi+r0tUARxPi5Sgdgrh8nc5san7D4tbApGdLbjP61ytAbaoLCJI0M6Ql2J8vkIZjeTcjUe1IrQ+DVmA6l50nQF8/xKcWn1wqhQ4+rzo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
