travis:
  secure:
    BINSTAR_TOKEN: 0hCcAVkyhZM7lzg1s0Jgh3QrZPKIggAPgwUd0G4Pp+TEHWS6xG8R7K5Tc/2wQaMBoHohObwhEAhJwH0heQxgmfBWwRi/5SO0QGS+mtYtoP76jDaSaAFk4J4yl2+w/KrMs0UANvj4JgAo0SrW2UQEChYbDwBzikGZmgAK1nuZCB/czNHCh73QtYx3Sarq+dba5MYXzxNOPpZOv/dkto8u1ugKY6lNcNYGI81veQUDa+GeVTBBkau9jpF89ufHtP2HHLQaOCFkSqZ5/gZdf33KIJyzBnRh385jB1exatfiaExzTBIS7FheSDAOfUP46Xdswn41yPMhyyPM0EmVqDFLD9Ze4/Z/hS7LXU6vODhRzWEywcBUFEnl31FZZOeVKSDY7oOZWaeQRXEPe4M4ctfogzQ63ExMs7I+YkE8YUVZQs2ouCMpbKn1dBDCuGb0pU7KgLGxJrjcCz0NNdBz8XqsNQzSWhmWbEP32mY8VVA4LrpgpffQAY00HbN8OD8x4TSV6Q3wRv100F5D74N2SAbOKa3ZwzWPct4nlNQMS661ModHEASphk++1hyrzmM/zPz9J5h1VFOCx+4ds8ARX+LXxCM55axF0/PhZetwzi0HlUs39LsYxGXoul1PxbtbY6eL9WfNC5AYfa6InfZtOfcUc3XXR3jGwp9bikjV6c+MfU0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
